yaml

steps:
  # Step 1: GCR 인증
  - name: 'gcr.io/cloud-builders/docker'
    id: AuthenticateGCR
    args:
      - 'auth'
      - 'configure-docker'
      - 'gcr.io'

  # Step 2: Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    id: BuildDockerImage
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/smart-k-festa-image:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/smart-k-festa-image:latest'
      - '.' # Dockerfile이 프로젝트 루트에 있다고 가정

  # Step 3: Python 의존성 설치 확인 (선택적)
  - name: 'gcr.io/cloud-builders/docker'
    id: VerifyPythonDependencies
    args:
      - 'run'
      - '--rm'
      - 'gcr.io/$PROJECT_ID/smart-k-festa-image:$COMMIT_SHA'
      - 'python3'
      - '-c'
      - 'import pkg_resources; [pkg_resources.get_distribution(p) for p in open("requirements.txt").read().splitlines() if p and not p.startswith("#")]'
    waitFor: ['BuildDockerImage']
    # 이 단계는 requirements.txt에 명시된 패키지가 설치되었는지 확인합니다.

  # Step 4: Docker 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    id: PushDockerImage
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/smart-k-festa-image'
    waitFor: ['BuildDockerImage', 'AuthenticateGCR']

# 푸시할 이미지 지정
images:
  - 'gcr.io/$PROJECT_ID/smart-k-festa-image'

# 글로벌 타임아웃
timeout: 2400s # 40분

# 로그 설정
options:
  logging: CLOUD_LOGGING_ONLY

