steps:
  # 사용할 베이스 이미지 선택 (Python 3.9)
  - name: 'python:3.9-slim'
    id: install_dependencies
    # 작업 디렉토리 설정 (저장소 루트)
    dir: /workspace
    # requirements.txt 파일이 있는 경우, 필요한 종속성 설치
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  # 실제 빌드 및 테스트 (예시)
  - name: 'python:3.9-slim'
    id: run_tests
    # 작업 디렉토리 설정 (저장소 루트)
    dir: /workspace
    entrypoint: 'python'
    # 테스트 실행 명령어 (예시)
    args: ['-m', 'unittest', 'discover']

# 빌드 결과 이미지 저장 (선택 사항, 필요한 경우)
images:
  - 'gcr.io/$PROJECT_ID/smart-k-festa-image'
